Repository java-book-study/TICKET-EXPEDITIONARY-FORCE, pull requests merged in 2020-12, with the labels that each got.

#54 [TICKET-92] ticket 패키지 코드 리팩토링
  src/main/java/com/ticket/captain/ticket/Ticket.java
  src/main/java/com/ticket/captain/ticket/TicketController.java
  src/main/java/com/ticket/captain/ticket/TicketService.java
  src/main/java/com/ticket/captain/ticket/dto/TicketCreateDto.java
  src/main/java/com/ticket/captain/ticket/dto/TicketDto.java
  src/main/java/com/ticket/captain/ticket/dto/TicketUpdateDto.java
  src/main/resources/application.yml
  src/test/java/com/ticket/captain/ticket/TicketControllerTest.java
  src/test/java/com/ticket/captain/ticket/TicketCreateDocumentationTests.java
  src/test/java/com/ticket/captain/ticket/TicketDeleteDocumentationTests.java
Labels: feature, fix, refactoring

#55 [TICKET-95] fix: 새로 변경된 DB 연결 및 autoDDL 옵션 해제
  build.gradle
  src/main/resources/application.yml
Labels: review skip

#57 [TICKET-96] DB와 맞지않는 컬럼 매핑 수정 (Festival, FestivalDetail)
  src/main/java/com/ticket/captain/festival/Festival.java
  src/main/java/com/ticket/captain/festivalDetail/FestivalDetail.java
Labels: bug, fix

#56 [TICKET-94] statusCode DB 'status_id'와 매핑하도록 @Column 추가
  src/main/java/com/ticket/captain/order/Order.java
Labels: fix

#58 [TICKET-97] Festival, FestivalDetail mapping url 변경
  src/main/java/com/ticket/captain/festival/FestivalManagerController.java
  src/main/java/com/ticket/captain/festival/FestivalUserController.java
  src/main/java/com/ticket/captain/festivalDetail/FestivalDetailRestController.java
Labels: refactoring
