Repository java-book-study/TICKET-EXPEDITIONARY-FORCE, pull requests merged in 2020-11, with the labels that each got.

#37 [TICKET-63] fix: Ticket Table Column 변경으로 인한 Ticket 로직 변경
  src/main/java/com/ticket/captain/config/security/SecurityConfig.java
  src/main/java/com/ticket/captain/ticket/Ticket.java
  src/main/java/com/ticket/captain/ticket/TicketController.java
  src/main/java/com/ticket/captain/ticket/TicketService.java
  src/main/java/com/ticket/captain/ticket/dto/TicketCreateDto.java
  src/main/java/com/ticket/captain/ticket/dto/TicketDto.java
  src/main/java/com/ticket/captain/ticket/dto/TicketUpdateDto.java
  src/main/resources/application.yml
  src/test/java/com/ticket/captain/ticket/TicketCreateDocumentationTests.java
  src/test/java/com/ticket/captain/ticket/TicketDeleteDocumentationTests.java
  src/test/java/com/ticket/captain/ticket/TicketListDocumentationTests.java
Labels: fix

#36 [TICKET-68] refactor : AccountDto 통합(AccountCreateDto 부분)
  src/main/java/com/ticket/captain/account/AccountCreateDtoValidator.java
  src/main/java/com/ticket/captain/account/AccountService.java
  src/main/java/com/ticket/captain/account/AccountSignupController.java
  src/main/java/com/ticket/captain/account/dto/AccountCreateDto.java
  src/main/java/com/ticket/captain/account/dto/AccountDto.java
  src/test/java/com/ticket/captain/account/AccountLoginControllerTest.java
  src/test/java/com/ticket/captain/account/AccountSignupControllerTest.java
Labels: fix, question, refactoring

#38 [TICKET-70] fix: resources/templates 폴더 내 html 제거 작업
  src/main/resources/templates/account/checked-email.html
  src/main/resources/templates/account/complete.html
  src/main/resources/templates/account/sign-up.html
  src/main/resources/templates/fragments/fragments.html
  src/main/resources/templates/index.html
  src/test/java/com/ticket/captain/account/AccountSignupControllerTest.java
Labels: fix

#40 feature/TICKET-72 : securityConfig appointment hasAnyRole MANAGER deleted
  src/main/java/com/ticket/captain/config/security/SecurityConfig.java
Labels: fix, refactoring

#41 [TICKET-76] refactor : AccountDto 부분 통합 해제
  src/main/java/com/ticket/captain/account/Account.java
  src/main/java/com/ticket/captain/account/AccountApiController.java
  src/main/java/com/ticket/captain/account/AccountCreateDtoValidator.java
  src/main/java/com/ticket/captain/account/AccountService.java
  src/main/java/com/ticket/captain/account/AccountSignupController.java
  src/main/java/com/ticket/captain/account/dto/AccountCreateDto.java
  src/main/java/com/ticket/captain/account/dto/AccountDto.java
  src/main/java/com/ticket/captain/account/dto/AccountUpdateDto.java
  src/test/java/com/ticket/captain/account/AccountApiControllerTest.java
  src/test/java/com/ticket/captain/account/AccountLoginControllerTest.java
  src/test/java/com/ticket/captain/account/AccountSignupControllerTest.java
Labels: fix, refactoring

#43 [TICKET-81] refactor: Order Entity 수정 및 TicketTest 변경
  src/main/java/com/ticket/captain/account/Account.java
  src/main/java/com/ticket/captain/festivalDetail/FestivalDetail.java
  src/main/java/com/ticket/captain/order/Order.java
  src/main/java/com/ticket/captain/order/StatusCode.java
  src/main/java/com/ticket/captain/ticket/Ticket.java
  src/main/java/com/ticket/captain/ticket/dto/TicketCreateDto.java
  src/main/java/com/ticket/captain/ticket/dto/TicketDto.java
  src/test/java/com/ticket/captain/ticket/TicketCreateDocumentationTests.java
  src/test/java/com/ticket/captain/ticket/TicketListDocumentationTests.java
Labels: bug, fix, refactoring

#45 TICKET-82 refactor: Spring Security HttpConfig import 되어있지 않아 추가
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
Labels: fix

#48 [TICKET-80] Order 생성자 구현
  src/main/java/com/ticket/captain/account/Account.java
  src/main/java/com/ticket/captain/order/Order.java
  src/main/java/com/ticket/captain/order/OrderController.java
  src/main/java/com/ticket/captain/order/OrderRepository.java
  src/main/java/com/ticket/captain/order/OrderService.java
  src/main/java/com/ticket/captain/order/dto/OrderDto.java
  src/main/java/com/ticket/captain/ticket/Ticket.java
  src/main/java/com/ticket/captain/ticket/dto/TicketDto.java
  src/test/java/com/ticket/captain/order/OrderServiceTest.java
Labels: feature, fix, refactoring

#50 [TICKET-86] fix: ticket 테이블 컬럼 변경으로 인한 도메인 수정
  src/main/java/com/ticket/captain/ticket/Ticket.java
  src/main/java/com/ticket/captain/ticket/dto/TicketCreateDto.java
  src/main/java/com/ticket/captain/ticket/dto/TicketDto.java
  src/main/java/com/ticket/captain/ticket/dto/TicketUpdateDto.java
Labels: bug, fix
