Repository java-book-study/TICKET-EXPEDITIONARY-FORCE, pull requests merged in 2020-10, with the labels that each got.

#9 [TICKET-23] RestDocs 추가 및 테스트코드 양식 추가
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/ticket/captain/CaptainApplication.java
  src/main/java/com/ticket/captain/config/SecurityConfig.java
  src/main/java/com/ticket/captain/config/SwaggerConfig.java
  src/main/java/com/ticket/captain/exception/NotFoundException.java
  src/main/java/com/ticket/captain/response/ApiResponseCode.java
  src/main/java/com/ticket/captain/response/ApiResponseDto.java
  src/main/java/com/ticket/captain/swagger/SwaggerController.java
  src/main/java/com/ticket/captain/ticket/Ticket.java
  src/main/java/com/ticket/captain/ticket/TicketController.java
  src/main/java/com/ticket/captain/ticket/TicketRepository.java
  src/main/java/com/ticket/captain/ticket/TicketService.java
  src/main/java/com/ticket/captain/ticket/dto/TicketCreateDto.java
  src/main/java/com/ticket/captain/ticket/dto/TicketDto.java
  src/main/java/com/ticket/captain/ticket/dto/TicketUpdateDto.java
  src/main/java/com/ticket/captain/utils/EnumType.java
  src/main/resources/application.properties
  src/main/resources/static/docs/index.html
  src/test/java/com/ticket/captain/ApiDocumentationTest.java
  src/test/java/com/ticket/captain/document/utils/ApiDocumentUtils.java
  src/test/java/com/ticket/captain/ticket/TicketCreateDocumentationTests.java
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: feature, settings

#10 [TICKET-35] feat: git PR 및 ISSUE 템플릿 설정
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#11 [TICKET-26] feat: 회원관리 API 만들기 및 구현
  src/main/java/com/ticket/captain/AccountAdvice.java
  src/main/java/com/ticket/captain/ErrorResponse.java
  src/main/java/com/ticket/captain/account/Account.java
  src/main/java/com/ticket/captain/account/AccountApiController.java
  src/main/java/com/ticket/captain/account/AccountRepository.java
  src/main/java/com/ticket/captain/account/AccountService.java
  src/main/java/com/ticket/captain/account/Address.java
  src/main/java/com/ticket/captain/account/Role.java
  src/main/java/com/ticket/captain/account/dto/AccountResponseDto.java
  src/main/java/com/ticket/captain/account/dto/AccountUpdateRequestDto.java
  src/main/java/com/ticket/captain/config/JsonConfig.java
  src/test/java/com/ticket/captain/account/AccountApiControllerTest.java
Labels: feature

#14 TICKET-25 jasypt 적용
  build.gradle
  src/main/java/com/ticket/captain/config/JasyptConfig.java
  src/main/resources/application.yml
  src/test/java/com/ticket/captain/JasyptEncryptionApplicationTest.java
Labels: feature, settings

#17 [TICKET-46] fix: jasypt gradle build시 systemProperties 가져오도록 설정
  build.gradle
Labels: bug, settings

#24 Release/ticket 53
  build.gradle
  src/main/java/com/ticket/captain/ErrorSerializer.java
  src/main/java/com/ticket/captain/account/Account.java
  src/main/java/com/ticket/captain/account/AccountAdvice.java
  src/main/java/com/ticket/captain/account/AccountApiController.java
  src/main/java/com/ticket/captain/account/AccountCreateDtoValidator.java
  src/main/java/com/ticket/captain/account/AccountRepository.java
  src/main/java/com/ticket/captain/account/AccountRepositoryCustom.java
  src/main/java/com/ticket/captain/account/AccountRepositoryCustomImpl.java
  src/main/java/com/ticket/captain/account/AccountService.java
  src/main/java/com/ticket/captain/account/AccountSignupController.java
  src/main/java/com/ticket/captain/account/AccountStatus.java
  src/main/java/com/ticket/captain/account/dto/AccountCreateDto.java
  src/main/java/com/ticket/captain/account/dto/AccountResponseDto.java
  src/main/java/com/ticket/captain/account/dto/AccountUpdateRequestDto.java
  src/main/java/com/ticket/captain/common/Address.java
  src/main/java/com/ticket/captain/common/ErrorsResource.java
  src/main/java/com/ticket/captain/config/AppProperties.java
  src/main/java/com/ticket/captain/config/JasyptConfig.java
  src/main/java/com/ticket/captain/config/JsonConfig.java
  src/main/java/com/ticket/captain/config/SecurityConfig.java
  src/main/java/com/ticket/captain/config/security/MyLoginFailureHandler.java
  src/main/java/com/ticket/captain/config/security/MyLoginSuccessHandler.java
  src/main/java/com/ticket/captain/config/security/SecurityConfig.java
  src/main/java/com/ticket/captain/festival/FestivalRestController.java
  src/main/java/com/ticket/captain/mail/EmailMessage.java
  src/main/java/com/ticket/captain/mail/EmailService.java
  src/main/java/com/ticket/captain/mail/HtmlEmailService.java
  src/main/java/com/ticket/captain/main/CurrentUser.java
  src/main/java/com/ticket/captain/main/MainController.java
  src/main/java/com/ticket/captain/response/ApiResponseDto.java
  src/main/java/com/ticket/captain/ticket/TicketController.java
  src/main/java/com/ticket/captain/utils/DateTimeUtils.java
  src/main/resources/application.yml
  src/main/resources/templates/account/checked-email.html
  src/main/resources/templates/account/complete.html
  src/main/resources/templates/mail/simple-link.html
  src/test/java/com/ticket/captain/ApiDocumentationTest.java
  src/test/java/com/ticket/captain/Festival/FestivalControllerTest.java
  src/test/java/com/ticket/captain/JasyptEncryptionApplicationTest.java
  src/test/java/com/ticket/captain/account/AccountApiControllerTest.java
  src/test/java/com/ticket/captain/account/AccountControllerTest.java
  src/test/java/com/ticket/captain/account/AccountLoginControllerTest.java
  src/test/java/com/ticket/captain/account/AccountSignupControllerTest.java
  src/test/java/com/ticket/captain/ticket/TicketCreateDocumentationTests.java
Labels: documentation, feature, settings
